### ISSUE TITLE
[DEV] Migrate Consistency Enforcement image to Alma9

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#654] opened 2023-11-21 22:23 UTC
Dockerfile: https://github.com/dmwm/CMSRucio/blob/master/docker/rucio-consistency/Dockerfile

**Comment by klannon** [comment] 2024-06-11 01:58
@ericvaandering @mrguilima This is marked as done in the project board, but the issue is still open.  Should it be closed?

**Closed** 2024-06-11 14:54 UTC
Labels: dev
