### ISSUE TITLE
Negative usage counters

### ISSUE THREAD

**Issue by juztas** [dmwm/CMSRucio#213] opened 2021-03-22 19:36 UTC
account usage shows negative values. See on slack cms channel for more details (Feb 23rd, 2020)
```
-bash-4.2$ rucio list-rse-usage T2_US_Caltech --show-accounts
USAGE:
...
------
  rse_id: a0c1b4ce18324a9d80ea60f16e8b485d
  rse: T2_US_Caltech
  source: rucio
  used: 1.797 PB
  files: 582404
  updated_at: 2021-02-23 18:33:07
  per account:
  ------
    account: wmcore_transferor               used: 744.259 TB                         percentage: 41.42
  ------
    account: wma_prod                        used: 345.891 TB                         percentage: 19.25
  ------
    account: sync_t2_us_caltech              used: 302.022 TB                         percentage: 16.81
  ------
    account: t2_us_caltech_local_users       used: 227.111 TB                         percentage: 12.64
  ------
    account: transfer_ops                    used: 169.976 TB                         percentage: 9.46
  ------
    account: crab_tape_recall                used: 57.498 TB                          percentage: 3.2
  ------
    account: wmcore_output                   used: 4.052 TB                           percentage: 0.23
  ------
    account: sync_t1_ru_jinr_disk            used: -7.279 MB                          percentage: -0.0
  ------
    account: piperov                         used: -1.775 GB                          percentage: -0.0
  ------
    account: dellaric                        used: -106.882 GB                        percentage: -0.01
  ------
....
------
```

**Comment by nsmith-** [comment] 2021-03-22 19:59
From Martin:
So there is two queries you can execute (These are PLSQL procedures/queries on oracle)
The first one updates the account usage to reflect what is in the locks table
```sql
-- Update/Resync account usage
BEGIN
         for l in (select account, rse_id, count(*) as length, sum(bytes) as bytes, sys_extract_utc(localtimestamp) as updated_at from locks group by account, rse_id )
         loop
             UPDATE account_usage SET files = l.length, bytes = l.bytes, updated_at=SYSTIMESTAMP
             WHERE account=l.account and rse_id=l.rse_id;
             COMMIT;
         end loop;
END;
```
And a second query, which basically resets all the rows which were not touched by this query (Which means that usage counter should be 0)
```sql
UPDATE account_usage SET files = 0, bytes=0, updated_at=SYSTIMESTAMP WHERE updated_at < SYSTIMESTAMP-1 and (files != 0 or bytes != 0);
```
You don’t need to stop anything in the system. There is the slight chance that if there is something added exactly in the wrong moment, that there might be small discrepancies, but in general it should be fine.
The first query might take a while, since it needs to scan the entire locks table

**Comment by yuyiguo** [comment] 2022-01-26 19:27
[ ~ 1007] date
Wed Jan 26 19:16:07 CET 2022
[ ~ 1007] rucio list-rse-usage T2_US_Caltech --show-accounts
....
USAGE:
------
  used: 49.155 GB
  rse: T2_US_Caltech
  updated_at: 2022-01-26 18:10:32
  source: expired
  rse_id: a0c1b4ce18324a9d80ea60f16e8b485d
------
  used: 0.000 B
  rse: T2_US_Caltech
  updated_at: 2022-01-26 18:10:28
  source: obsolete
  rse_id: a0c1b4ce18324a9d80ea60f16e8b485d
------
  files: 713605
  used: 2.018 PB
  rse: T2_US_Caltech
  updated_at: 2022-01-26 18:14:33
  source: rucio
  per account:
  ------
    account: t2_us_caltech_local_users       used: 882.407 TB                         percentage: 43.72                        
  ------
    account: wma_prod                        used: 584.763 TB                         percentage: 28.97                        
  ------
    account: transfer_ops                    used: 479.119 TB                         percentage: 23.74                        
  ------
    account: wmcore_transferor               used: 350.996 TB                         percentage: 17.39                        
  ------
    account: wmcore_output                   used: 10.480 TB                          percentage: 0.52                         
  ------
    account: crab_tape_recall                used: 1.208 TB                           percentage: 0.06                         
  ------
    account: sync_t2_us_caltech              used: 150.494 GB                         percentage: 0.01                         
  ------
    account: sync_t2_fr_ccin2p3              used: 74.945 GB                          percentage: 0.0                          
  ------
    account: sync_t1_ru_jinr_disk            used: -7.279 MB                          percentage: -0.0                         
  ------
    account: piperov                         used: -1.775 GB                          percentage: -0.0                         
  ------
    account: dellaric                        used: -106.882 GB                        percentage: -0.01                        
  ------
  rse_id: a0c1b4ce18324a9d80ea60f16e8b485d
------
  used: 2.000 PB
  rse: T2_US_Caltech
  updated_at: 2021-02-11 17:25:26
  source: static
  rse_id: a0c1b4ce18324a9d80ea60f16e8b485d
------
  used: 206.837 TB
  rse: T2_US_Caltech
  updated_at: 2022-01-26 19:00:00
  source: unavailable
  rse_id: a0c1b4ce18324a9d80ea60f16e8b485d
  
I found below:
1. query account_useage table with files<>0 and account= piperov, nothing was return.  
```
account    rse_id.                                                               files.  bytes.             updated_at
piperov	087EE3383B9D45F6B31814AF07B2C56D	-4	-1775092138	2020-07-11 12:50:52	
piperov	32DE67834EF642B89FD272FED9DAC060	-1	-25135799	2020-07-11 12:50:52	
piperov	A0C1B4CE18324A9D80EA60F16E8B485D	-4	-1775092138	2020-07-11 12:50:52	
piperov	A6981DEE6ED14B7C8C1B0E9FE7644401	-4	-1775092138	2020-07-11 12:50:52	
piperov	BE0C1696016E4297A1573425D4A9B0A6	65	125054612833	2021-09-24 21:25:26	
piperov	C8100BE288104B2A87E6795968818D81	1024	643433398394	2020-07-11 12:50:52	
piperov	D34EAFE13F8C467A8D599587C8C15F00	-1	-44239473	2020-07-11 12:50:52	
piperov	DBDAF50EE9D24F92AD24473539522204	-4	-1775092138	2020-07-11 12:50:52	
piperov	DD251C7F3F7A40E0B3AEF3D2C6D0875E	-4	-1775092138	2020-07-11 12:50:52	
piperov	E1C33AB333304B33B1E283BEA046E112	-8	-3550184276	2020-07-11 12:50:52
piperov	EF60517710A34124A8148D23556A627D	-4	-1775092138	2020-07-11 12:50:52
```
The table was not updated since last July. Do we have a cron job running the scripts mentioned by Martin?

**Comment by yuyiguo** [comment] 2022-01-31 02:45
Copied from Slack

Nick Smith  3:04 PM
should be one of the abacus daemons updating that table. so it makes sense for some rows to not be updated since a long time but other rows in that table should be new (edited) 

Yuyi  3:10 PM
It would be nice to know what scripts used by the abacus daemons. Should it run the same scripts in the ticket?

Yuyi  3:55 PM
```
https://github.com/rucio/rucio/blob/86b27bcb485f92759eae25b93b9efb9f7e4103c0/etc/sql/oracle/procedures.sql#L125
https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/etc/sql/oracle/jobs.sql#L12
```
These two seems update/merge account_usage table, but the jobs we are running are:
```
UPDATE_RSE_USAGE_HISTORY	SCHEDULED
RUCIO_DATA_SLIDING_WINDOWS	SCHEDULED
RULES_HIST_SL_WINDOW	SCHEDULED
RUCIO_ACCOUNT_USAGE_HIST_JOB	SCHEDULED
COLL_REPL_UPDATED_JOB_CMS	SCHEDULED
@Martin Barisits Can you explain here?
```
Martin Barisits:house_with_garden:  4:33 AM
Yes you need the two jobs ABACUS_ACCOUNT and ABACUS_RSE scheduled by UPDATE_ACCOUNT_COUNTERS and UPDATE_RSE_COUNTERS
These two check updated accounts/rses and update the account_usage and rse_usage tables.
The history ones above regularly fetch the values from these tables and update their respective history tables, so you have timeseries of that data as well.
As Nick pointed out, alternative is running the abacus daemons, but since you already have the other oracle jobs, it’s better to do that.
be careful, if your updated_account_counters and updated_rse_counters tables are very big now, I am not sure if the jobs initially will run through fine. In this case, empty out the tables, call the two scripts linked in the ticket (it’s to reset the usage to correct values) and then just go from there.

**Comment by yuyiguo** [comment] 2022-01-31 03:10
More study found that we have `daemons-abacus-account` running script  `rucio-abacus-account `.  The script updates various tables every 10 ish minutes.   
```
select max(UPDATED_AT) from account_usage;
2022-01-31 02:40:51
```
So the usage table are updated continuously. 

```
select count(*) from updated_rse_counters;
5
select count(*) from updated_account_counters;
2
```
For some reason,  part of `account_useage table ` had stale data. 

So we will follow instructions from Martin (in this TK) to update account_usage table using locks table data, the remove the stale data  that is not touched by the update.

**Comment by yuyiguo** [comment] 2022-01-31 21:07
The problem is fixed by running the two scripts. I had some problem to with the scripts due to some of the table lock problem caused by interrupted sqls. 
I did a quick test below:
rucio list-rse-usage T2_US_Caltech --show-accounts
….
```
------
 files: 712565
 used: 2.015 PB
 rse: T2_US_Caltech
 updated_at: 2022-01-31 20:39:52
 source: rucio
 per account:
 ------
  account: t2_us_caltech_local_users    used: 882.365 TB             percentage: 43.78             
 ------
  account: wma_prod            used: 576.660 TB             percentage: 28.61             
 ------
  account: transfer_ops          used: 482.951 TB             percentage: 23.96             
 ------
  account: wmcore_transferor        used: 350.206 TB             percentage: 17.38             
 ------
  account: wmcore_output          used: 12.561 TB             percentage: 0.62             
 ------
  account: crab_tape_recall        used: 1.292 TB              percentage: 0.06             
 ------
  account: sync_t2_fr_ccin2p3       used: 74.945 GB             percentage: 0.0              
 ------
 rse_id: a0c1b4ce18324a9d80ea60f16e8b485d
------
```

**Comment by dynamic-entropy** [comment] 2023-06-22 05:11
Hi @yuyiguo 

I still see the issue, 
```
➜  ~ rucio list-rse-usage T2_US_Caltech --show-accounts
......
......
......

  ------
    account: wma_prod                        used: 817.207 TB                   percentage: 28.44 
  ------
    account: transfer_ops                    used: 697.818 TB                   percentage: 24.29  
  ------
    account: t2_us_caltech_local_users       used: 270.103 TB                  percentage: 9.4  
  ------
    account: wmcore_transferor               used: 258.486 TB                   percentage: 9.0
  ------
    account: wmcore_output                   used: 3.130 TB                     percentage: 0.11 
  ------
    account: crab_tape_recall                used: 1.831 TB                     percentage: 0.06  
  ------
    account: sync_t2_fr_ccin2p3              used: 74.945 GB                    percentage: 0.0  
  ------
    account: tier0_prod                      used: -704.707 GB                  percentage: -0.02   👈
  ------
  rse: T2_US_Caltech
------

......
......
......
```

Additionally, it appears to be the case with `list-account-usage` and thus the corresponding table as well. 
```
➜  ~ rucio list-account-usage tier0_prod                                 
+----------------------+-------------+------------+--------------+
| RSE                  | USAGE       | LIMIT      | QUOTA LEFT   |
|----------------------+-------------+------------+--------------|
| T0_CH_CERN_Disk      | 224.008 TB  | 0.000 B    | 0.000 B      |
| T0_CH_CERN_Disk_Test | 14.569 TB   | 0.000 B    | 0.000 B      |
| T0_CH_CERN_Tape      | 27.637 PB   | 0.000 B    | 0.000 B      |
| T1_DE_KIT_Disk       | 616.857 TB  | 0.000 B    | 0.000 B      |
| T1_DE_KIT_Tape       | 2.196 PB    | 0.000 B    | 0.000 B      |
| T1_ES_PIC_Disk       | 233.908 TB  | 0.000 B    | 0.000 B      |
| T1_ES_PIC_Tape       | 1.450 PB    | 0.000 B    | 0.000 B      |
| T1_FR_CCIN2P3_Disk   | 420.304 TB  | 0.000 B    | 0.000 B      |
| T1_FR_CCIN2P3_Tape   | 2.414 PB    | 0.000 B    | 0.000 B      |
| T1_IT_CNAF_Tape      | 1.236 PB    | 0.000 B    | 0.000 B      |
| T1_RU_JINR_Disk      | 9.521 TB    | 0.000 B    | 0.000 B      |
| T1_RU_JINR_Tape      | 73.968 TB   | 0.000 B    | 0.000 B      |
| T1_UK_RAL_Tape       | 757.112 TB  | 0.000 B    | 0.000 B      |
| T1_US_FNAL_Disk      | 1.921 PB    | 0.000 B    | 0.000 B      |
| T1_US_FNAL_Tape      | 11.364 PB   | 0.000 B    | 0.000 B      |
| T2_CH_CERN           | 4.405 PB    | 0.000 B    | 0.000 B      |
| T2_US_MIT_Tape       | 447.587 TB  | 0.000 B    | 0.000 B      |
| T2_US_Vanderbilt     | -360.600 GB | 100.000 TB | 100.361 TB   |   👈 
+----------------------+-------------+------------+--------------+
```

**Comment by yuyiguo** [comment] 2023-06-28 16:59
@ericvaandering 
Can you give me permission to list account usage?
[yuyi@lxplus805 ~ 1013] rucio list-account-usage tier0_prod     
2023-06-28 18:56:05,291	ERROR	Access to the requested resource denied.
Details: Account yuyi can not list account usage.

**Comment by yuyiguo** [comment] 2023-06-29 22:51
For unknown reason rucio account-usage table got negative numberof files or bytes.  When this happened, we have to re sync the usage table from the locker table. Now all the above commands gave the correct numbers. Altals use Oracle store procedures to sync, we are using daemons to snyc.   We will need to study the difference.

**Closed by yuyiguo** 2023-06-29 22:51 UTC

**Comment by dynamic-entropy** [comment] 2023-06-30 06:00
Hi @yuyiguo 
What did you have to do to fix this? Did you have to resync the tables manually
-  how is that done? 

or did it happen by itself? 
- In which case I suspect this will happen again, given the ticket is 2 years old, and I still saw the discrepancies last week.
