### ISSUE TITLE
Investigate automatic suspicious replica recovery

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#403] opened 2023-01-13 13:12 UTC
Would need something done with traces (declaring things suspicious, maybe some logic to deal with xrootd and specific exit codes?) 

Then need to run the replica recoverer daemon.

**Comment by yuyiguo** [comment] 2023-01-17 19:32
@ericvaandering ,
Can you give more details on this issue?

**Comment by belforte** [comment] 2023-01-20 10:01
@yuyiguo @ericvaandering I guess I am the one who started this.  Shall we try to have a quick chat on zoom ?
I am generally/usually available in your early morning (8-10), But if you prefer that I expand here.. sure, let me know.

**Comment by yuyiguo** [comment] 2023-01-20 15:03
Yes, I am available today. Let me know when we can chat.

**Comment by belforte** [comment] 2023-01-20 17:42
wel... today I had things to do. Let's plan it a little bit so that Eric may also join. 10 min should suffice

**Comment by belforte** [comment] 2023-01-23 17:33
what about tomorrow in your 8-10am window ?

**Comment by belforte** [comment] 2023-01-24 16:09
Adding some description after a chat with Eric and Yuyi
( I will get back to this and edit, but need to take a breal, so am saving it)
* where we start from
   *  in [this meeting](https://indico.cern.ch/event/1222966/)  Dimitrios Christidis reported in [slide 11](https://indico.cern.ch/event/1222966/contributions/5144936/attachments/2557128/4406749/2022.11.30%20Old%20and%20Unused%20Data%20Management%20with%20Rucio%20at%20ATLAS.pdf)  that
      *  For each failed transfer, if the error message matches some pattern, then the replica is marked as suspicious. The Rucio Replica Recoverer daemon processes these and does automatic recovery
 
* what we want to do
   * use that Replica Recover daemon to automatically check and fix files which we suspect of being corrupted because they make cmsRun(CMSSW) raise a fatal exception when reading.
 
* things we know
   1. cmsRun sends UDP messages when it closed files which it read successfully, those are turned somehow/somewhere into messages to AMQ which we (CMS) consume (some daemon which Yuyi is in control of)
   2. the path above is not viable to report read failures, since in that case cmsRun just exit via a fatal exception and has no way to go through the UDP-sending part
   3. there are other AMQ queues which are consumed by Yuyi's daemon and where we coudl send the information about bad files. In particular one
   4. Rucio client has `def declare_suspicious_file_replicas(self, pfns, reason)` in lib/rucio/client/replicaclient.py
   5. That

* things we should do

**Comment by dciangot** [comment] 2023-02-22 09:28
did this issue follow up somewhere else? Or is it just stale and we still need to validate @belforte proposal with the various tasks?

**Comment by belforte** [comment] 2023-02-22 12:58
is still on my todo list and I am not tracking it elsewhere. I should. Then this can be put on hold until I have a proposal.

**Comment by yuyiguo** [comment] 2023-02-22 15:56
This is on my to-do list too but in a low priority.

**Comment by yuyiguo** [comment] 2023-03-23 20:51
Looked into the list that @belforte put there. It helped me to form my thoughts below.
1. We as CMS already have FJR to WMArchive, to AMQ, and to Rucio Kronos.  If WMArchive can get the failed file info into AMQ, then I can get it to Rucio Kronos. Since WMArchive already parses FJR, I don't see there is any problem if FJR has the info. 
2. Rucio replicas table has` state`, the current values are:  `B, C, A, U, D`.  We may add `S` for suspicious.
3. We need to investigate Rucio’s ReplicaRecoverer daemon works and how it can use the data in `replicas` table.

**Comment by yuyiguo** [comment] 2023-03-28 02:35
What is the definition of "suspicious replicas"?  If a transfer failed, fts will try to retransfer it.  If the failure is permanent, how Replica Recover daemon can fix it?  Why CMSSW or processing jobs will read a suspicious replica?

**Comment by belforte** [comment] 2023-03-28 07:45
Hi @yuyiguo . Let me try to list here what I (think that I) understand. Hopefully it answers some of your questions.

1. If we plan to use [declare_suspicious_file_replicas](https://rucio.cern.ch/documentation/client_api/replicaclient/#declare_suspicious_file_replicas) definition is up to us.
2. Current wisdom is to check cmsRun stdout for fatal errors during root readout, we may have to collect some telling strings and improve with time.
3. ATLAS does a `rucio download` of each files to the WN before reading, so Rucio will verify checksum there and IIUC automatically mark replica as suspicious. I have tested this myself [1] and the error is duly detected, but I think something else is needed to mark the replica as suspicious, Most likely there's something else going one when ATLAS jobs try to read files and we need to ask  Dimitrios to be more explicit than in his talk mentioned in comment above. Anyhow we do not download files from storage to WN's.
4. We do not know why replicas get corrupted, most likely it is due to some problem with site's storage systems, as you say FTS transfers are expected to verify checksums. While of course, sometimes a bit can still be flipped in last step of file write/close and one only notices when file is read back.
5. data processing jobs do not know that a given replica is corrupted, so they read it and fail. I do not know what will happen if replica is marked suspicious. We only process datasets/blocks which are marked as AVAILABLE in a Disk RSE in Rucio, I can't say how a SUSPICIOUS replica affects that. Anyhow currently bad replicas stay on disk until manually removed by DM operators.
6. and finally, about how Replica Recover can fix it, all that I know is [this](https://github.com/rucio/rucio/blob/bc71856931bf8384fb6715b1ae977a32ef30a0ac/bin/rucio-replica-recoverer#L17-L20) and I can't say if this is really what is in use for ATLAS. I have not tried to read the [daemon code](https://github.com/rucio/rucio/blob/master/lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py) itself, but it has more comments with details. I definitely have no clue what `metadata` means here.

Hope this helps !


[1]
```
belforte@lxplus701/belforte> rucio download cms:/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_2_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v1/30000/BAA88CF6-7C17-ED11-8883-34800D2F7FF0.root --rses T2_US_UCSD
2023-03-27 17:57:51,728	INFO	Processing 1 item(s) for input
2023-03-27 17:57:51,847	INFO	No preferred protocol impl in rucio.cfg: No section: 'download'
2023-03-27 17:57:51,848	INFO	Using main thread to download 1 file(s)
2023-03-27 17:57:51,848	INFO	Preparing download of cms:/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_2_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v1/30000/BAA88CF6-7C17-ED11-8883-34800D2F7FF0.root
2023-03-27 17:57:51,866	INFO	Trying to download with davs and timeout of 4713s from T2_US_UCSD: cms:/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_2_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v1/30000/BAA88CF6-7C17-ED11-8883-34800D2F7FF0.root 
2023-03-27 17:57:51,936	INFO	Using PFN: davs://redirector.t2.ucsd.edu:1095/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_2_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v1/30000/BAA88CF6-7C17-ED11-8883-34800D2F7FF0.root
2023-03-27 17:59:58,713	WARNING	Checksum validation failed for file: cms:/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_2_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v1/30000/BAA88CF6-7C17-ED11-8883-34800D2F7FF0.root
2023-03-27 17:59:58,714	WARNING	Download attempt failed. Try 1/2
2023-03-27 18:02:02,656	WARNING	Checksum validation failed for file: cms:/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_2_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v1/30000/BAA88CF6-7C17-ED11-8883-34800D2F7FF0.root
2023-03-27 18:02:02,657	WARNING	Download attempt failed. Try 2/2
2023-03-27 18:02:02,670	ERROR	Failed to download file cms:/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_2_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v1/30000/BAA88CF6-7C17-ED11-8883-34800D2F7FF0.root
2023-03-27 18:02:02,672	ERROR	None of the requested files have been downloaded.
belforte@lxplus701/belforte>
```

**Comment by belforte** [comment] 2023-03-28 07:53
btw, the file in my example above has been fixed by Felipe and download is now OK.
https://mattermost.web.cern.ch/cms-o-and-c/pl/uw4mauamr3dxmf1aebpfsybcjo
https://ggus.eu/?mode=ticket_info&ticket_id=160902

**Comment by ivmfnal** [comment] 2023-08-01 22:00
Some time ago I wrote this [document](https://docs.google.com/document/d/1R9n1c2s1iXeCel5bHDTz7xPWdVVhZOqkUQv4o2PUaxs/edit?usp=sharing) with the proposal how we can handle this.
Has anybody had a chance to read it ?
Do we need to revisit that proposal ? I am a bit confused about the state of that proposal.

**Comment by ivmfnal** [comment] 2023-08-02 15:29
Basically here is my proposal:
1. Detection
   * Add code to WM and other similar activities to report a replica as "suspicious" to Rucio on a read error via standard Rucio interfaces (API or CLI)
   * Write instructions for individual users how to do the same 
2. Recovery. Configure existing Rucio suspicious_replica_recoverer to declare the replica as "bad" after so many detections. Once the replica is declared "bad", Rucio will re-replicate it. We can discuss separately the case when this replica is in fact last replica for the file.

I would like to get some feedback on this proposal. Perhaps we can add more details to it.
Once we agree on the plan, we can work out the details.

**Comment by belforte** [comment] 2023-08-02 15:48
thanks Igor, and apologies for not having replied earlier.
I had indeed read your document and fully agree with it and the plan outlined above.
I have in, and reasonably close to the top of my list,  to do the 1. above in CRAB: https://github.com/dmwm/CRABServer/issues/7548

I would like to see this at work from automatic/automated tools for a while, before we think about enabling users, at that point we may have to introduce some way to "trust machines more than humans" IMHO.

One thing that I expect we can talk about later, but let me mention now:
we can detect both missing and possibly corrupted files, and tell one from the other.
Should we also flag the missing ones (i.e. clean open failures w/o a zip error or wrong checksum) as suspicious and sort of try to shortcut the CE ? I am a bit worried when looking at [CE page](https://cmsweb.cern.ch/rucioconmon/ce/index) by how many sites simply fail week after week to give any useful result, looks only half sites or so have a "done". I am not saying to abandon that effort, simplt complement it.

We can surely resume this once I have code which parses CMSSW stderr !

**Comment by ivmfnal** [comment] 2023-08-02 17:28
Stefano @belforte , thanks for the reply and the feedback. I appreciate it.

I was thinking that it would make a sense to have another meeting (I think we had one already some time ago) among involved people to re-sync, discuss use cases and maybe come up with an action plan.

I think we need to get at least @yuyiguo @dynamic-entropy (Rahul) @klannon there. I would invite @ericvaandering too but he is on vacation. Who am I missing ?

**Comment by ivmfnal** [comment] 2023-08-02 17:38
@belforte said: "we can detect both missing and possibly corrupted files, and tell one from the other."

I think it is important to differentiate between several types of failures.

I would add another dimension to this:
* potentially recoverable failures - those which have chances to be caused by some transient condition like networking failure of the site downtime
* non-recoverable failures - e.g. checksum/file size/file format error - conditions which are unlikely to fix themselves

My understanding of the problem is that we want to use the "suspicious" replica state in first case for a while before we declare the replica "bad" if things do not improve, whereas if we believe this is not recoverable error, then go straight to "bad" replica state.

**Comment by belforte** [comment] 2023-08-03 09:06
I do not think we need a (longish( meeting now. I'd like to have code which parses stdout/stder and does a few "mark as suspiciou" first. There can be questions arising during that which we can address as needed. In a way, I have my action plan.
Maybe simply  a 5-min slot in usual CMS-Rucio dev meeting to make sure that everybody agrees with the plan which you outlined ? I think you missed @dciangot , anyhow this is not urgent IMHO.

As to the recoverable vs. non-recoverable. Yes, I know, we already discussed in the meeting where you firstly presented this. The problem here is how to be sure that the specific error is really a bad file, not a transient problem in the storage server, is the file really truncated, or was a connection dropped somewhere ? So again, I'd like to get experience with the simpler path first. All in all CRAB already retries file read failures 3 times (and WMA 10, IIUC), so if we e.g. say "3 time suspicious = bad", it may be good enough.

**Comment by belforte** [comment] 2023-08-03 14:08
Igor, can you translate that in English ?

**Comment by ivmfnal** [comment] 2023-08-03 14:09
> Igor, can you translate that in English ?

I am afraid not yet

**Comment by klannon** [comment] 2023-08-08 01:06
Would it make sense to start to collect data on bad replicas by filling the database, but wait to decide how to act on it until we have accumulated enough data in the database to understand that patterns.  I don't think it's so bad if we occasionally "recover" a replica that's not really bad if most of the time the recoveries are really targeting corrupted files.  But it would be nice to have some quantification of what "occasionally" and "most of the time" actually look like in practice.

**Comment by KatyEllis** [comment] 2023-08-08 09:52
That sounds good to me @klannon

**Comment by belforte** [comment] 2023-08-08 15:05
Could Rucio detect that file is OK when it goes to fix the bad replica ?
I do not see a way for the client, when it correctly opens a file, to check if by any chance someone flagged it as suspicious and repair that flag.
But what is really the concern here ? That were was some intermittent error which got resolved by itself so we waste one re-transfer ?
Let's see how many re-transfers we do first !

**Comment by ivmfnal** [comment] 2023-08-08 15:38
I guess that brings us back to more fundamental question: why not declare the replica as bad right away and risk an unneeded re-transfer ?

Is not why we are even discussing this - to not react to transient, self-recoverable errors ?

**Comment by belforte** [comment] 2023-08-08 15:52
> why not declare the replica as bad right away and risk an unneeded re-transfer ?

yeah.. we need to pick a number of failures which gives us some confidence that it is really bad. 1 is a good choice. 3 is also a good choice. 10 seems over conservative to me.  We need experience. The question is how to collect that experience w/o writing so much stuff that we spend all time debugging successful open reporting and its (over)load on the system.

Lacking that info we can simply count how many replicas we end up marking as bad. If number is low when wating for 3 suspicious report, we can lower. Or start with 1 and possibly increase.

**Comment by ivmfnal** [comment] 2023-08-08 15:57
Here are 2 suggestions:

Aggressive: 
Set the threshold to 1 (declare the replica as bad right away) and see if we see some problems. If we do , increate the threshold.

Conservative:
Set the threshold to 5 and time window to ... week (?) and use the suspicious_replica_recoverer to declare the replica as bad and see if we have some problems. If we do, adjust the threshold.

**Comment by belforte** [comment] 2023-08-08 21:05
> Here are 2 suggestions:

let's wait until
1) I manage to mark suspicious replicas
2) we agree that it is done correctly
3) we have an idea of how often it happens

I plan to resubmi jobs which failed because of this, so 3 "tags" are somehow guaranteed to arrive in O(1 day) if problem is real.

I understand that ball in on my side atm. Will do my best to kick it back to you !

**Comment by huangch-fnal** [comment] 2023-08-09 05:32
As a site operator, here is my two cents:

1. At FNAL, we constantly watching "corrupted" files. In T1_US_FNAL_Disk (a dCache storage), we have, now, 482 "bad" files among all 52916776 files. So, files getting corrupted in the storage is rare. Usually we do not have to deal with them until users complain, which (hitting bad files) is rare, too. Once in a blue moon, we would actively clean them up. If, all of a sudden there are many corrupted files, something major is happening. An external "fix" might not fix it.
2. In failed transfers, if the same source file, regardless of the destinations, consistently gives the same wrong checksum, we are pretty sure it is corrupted at source. For example, on August 7, in the past 24 hours, we saw davs://xrootd-local.unl.edu:1094/store/mc/RunIISummer20UL17MiniAODv2/BToJpsi_JPsiToMuMu_BMuonFilter_HardQCD_TuneCP5_13TeV-pythia8-evtgen/MINIAODSIM/NoPU_106X_mc2017_realistic_v9-v1/30000/3F9CC6E8-121B-CB4E-B7F4-B8CC8CCB5749.root had 15 transfer failures all ended up with "TRANSFER [5] DESTINATION CHECKSUM MISMATCH Source and destination ADLER32 do not match (b270048f != d64a7676) ". We got this information by scanning FTS (in terms of gfal) log. The same information should be in Rucio, too.
3. If the corrupted file is in Disk instance (no tape backend), usually replacing the file, if possible, is the remedy. There is a caveat. In dCache, a "hot" file might have multiple copies in multiple pools (to increase its availability and throughput). The transfer might just hit a bad copy. In that case, the remedy is to remove that bad copy without deleting other ones. An external replacement would effectively kill the other copies.
4. If the corrupted file is in Tape instance, there is a high probability that the tape copy is good while the copy in the pool is corrupted (stage error), otherwise, the checksum mismatch would have been discovered when the file was written to tape. In this case, we removed the copy from the pool and re-stage the file again. This is very rare and broken files in the pool would be discovered by dCache. In T1_US_FNAL_Tape, there is, now, 0 corrupted files in all pools.
5. known corrupted files can be dealt with appropriately.

The signature for "missing file" is "not exist" (in the namespace). The response is pretty quick. The remedy is to copy the file.

If the file is in the namespace but not available, usually it indicates a hardware issue or a system issue. An automatic replacement might NOT solve the problem and might, very likely, create a new (problem). The best way is to notify the site. They might have already been working on it.

If the transfer timed out, there are many possibilities and would be very hard to do (fix) it right. We might "flag" it but not fixing it.

Keep in mind that we are dealing with program bugs from time to time (guess who put the bugs in there? developers!). Whatever we do must have a safeguard and whatever "automatic fix" should have an option to opt out by site. Whatever we do, automatically or not, the site must be notified.

**Comment by ivmfnal** [comment] 2023-08-09 13:05
@huangch-fnal Chih-Hao, thanks for your input.

Let me try to summarize your feedback in terms of condition-action pairs:

1. Bad chacksum - irrecoverable - declare the replica "bad"
2. File not found - irrecoverable - CE will detect it within a week and declare as "bad"
3. File unavailable - recoverable - wait, notify the site
4. Timeout - recoverable - wait, notify the site

Did I get it right ?

**Comment by huangch-fnal** [comment] 2023-08-15 12:37
Close. 3. and 4. may or may not be recoverable.
To sum up, transfer failure due to actually corrupted file is rare. In all cases, the site should be notified. At FNAL, we are not in favor of automatic recovery unless it is proven safe.

**Comment by belforte** [comment] 2023-09-04 16:58
here's a fresh example of corrupted file (at T2_US_Florida)
https://cms-talk.web.cern.ch/t/corrupted-doublemuon-miniaod-file/29163

I am happy to know that this will never happen at FNAL, but I do not see why there should any question in such cases about automatically declare the replica bad and trigger a re-transfer from tape.
What do you think @huangch-fnal  ? Would any harm happen in such a case ? One aim we have here is also to avoid bugging site admins unelss absolutely needed, i.e. after all that could be done by machines, failed.

@ivmfnal In this example the user retried  the job14 times ! Can we assume that once CRAB declares the replica suspicious maybe "only" 6 times, the automatic part can kick in ?
I'd rather not wait a week, though.

**Comment by ivmfnal** [comment] 2023-09-04 17:34
@belforte my understanding is that the replica recoverer can be configured like that

**Comment by ivmfnal** [comment] 2023-09-04 17:51
to get file count, use API function:
```
   get_dataset(did=None, namespace=None, name=None, exact_file_count=False)
```

Keep in mind though that getting file count will take time proportional to the number of files in the dataset

**Comment by belforte** [comment] 2023-09-11 13:29
@ivmfnal @ericvaandering @dciangot 
I have started with code to report bad files in CRAB.
But I have found that cmsRun output does not provide (clear) information on whether the file open attempt was local, or on a remote site via xrootd. So I do not have a good way to say which is the RSE (or the pfn required by Rucio).

Is there a way to report to rucio only a suspicious DID, and have it figure out which of the possible multiple disk replicas is corrupted ? Or do we need an additional daemon on our side , somewhere ?

See e.g the example in https://github.com/dmwm/CRABServer/issues/7548#issuecomment-1713880031
even if the bad file is at CERN, cmsRun reports
```
      [c] Fatal Root Error: @SUB=TStorageFactoryFile::Init
file root://cmsxrootd.fnal.gov//store/user/belforte/truncatedFile.root is truncated at 52428800 bytes
```

**Comment by ericvaandering** [comment] 2023-09-11 14:03
No, Rucio doesn’t have any innate checking abilities like this. 

The “daemon” you suppose would try reading every file directly over xrootd to find the corrupted one(s)?

**Comment by belforte** [comment] 2023-09-11 14:13
or do a rucio get which check checksum

**Comment by ivmfnal** [comment] 2023-09-11 14:18
would not it be easier to have CRAB be specific which replica failed to read ?

**Comment by belforte** [comment] 2023-09-11 14:21
CRAB needs that CMSSW if the error happened opening a local file or a fallback one.
See my example. The corrupted file is at CERN, cmsRun only mentions FNAL :-(

**Comment by ivmfnal** [comment] 2023-09-11 14:27
I know.
Would not it be easier to have CRAB tell which replica was corrupt - the remote or the local ?

**Comment by ericvaandering** [comment] 2023-09-11 15:17
I wasn't suggesting that you need to write or run it. Just the process you are suggesting. WMAgent will probably run into the same issue. 

So I understand the problem:

CRAB gets this error from CMSSW but CMSSW does not give enough information to know if the file is read locally or remotely?

Then, even if we knew "remotely" I could imagine problems knowing *which* remote file was read. CMSSW may not have any way of knowing that.

**Comment by belforte** [comment] 2023-09-11 17:14
(somehow) later on we can think of incorporating all that code into something that parses cmsrun stdout and makes a call to Rucio on the fly. But I am not sure that we want to run Rucio client in WorkerNodes. It should be available since it is on cvmfs.
I guess I will not post more for a bit, while I try to map what's the situation out there.

**Comment by ericvaandering** [comment] 2023-10-20 01:54
I finally found my notes from a discussion with @ivmfnal and Cedric regarding this, so I paste them here. This would help us declare suspicious replicas. What we'd need to start investigating again is how to move things from suspicious to bad. There was a way to do that too and I've forgotten.

```
# rucio-admin config get --section conveyor --option suspicious_pattern
[conveyor]
suspicious_pattern=.*No such file or directory.*,.*CHECKSUM MISMATCH Source and destination checksums do not match.*,.*SOURCE CHECKSUM MISMATCH.*,.*Unable to read file - wrong file checksum.*,.*checksum verification failed.*
# rucio-admin config get --section kronos --option bad_files_patterns
[kronos]
bad_files_patterns=.*No such file or directory.*,.*no such file or directory.*,.*CHECKSUM MISMATCH Source and destination checksums do not match.*,.*SOURCE CHECKSUM MISMATCH.*,.*Unable to read file - wrong file checksum.*,.*checksum verification failed.*,.*direct_access.*,.*Copy failed with mode 3rd pull, with error: Transfer failed: failure: Server returned nothing.*,.*HTTP 404 : File not found.*
```
Here is the part of the code responsible for the declaration in the conveyor : https://github.com/rucio/rucio/blob/master/lib/rucio/daemons/conveyor/finisher.py#L301-L331
and in kronos : https://github.com/rucio/rucio/blob/master/lib/rucio/daemons/tracer/kronos.py#L131-L147
As you can see, for kronos, the traces are expected to have some specific key/values

**Comment by belforte** [comment] 2023-10-20 10:31
I will report in here as well what I wrote in the MM channel.
CRAB has been running now for 11 days in a mode where it reports (via files on EOS) all occurences of FatalRootError,
so far only a few cases of "error in reading from an otherwise good file replica" have surfaced.
https://github.com/dmwm/CRABServer/issues/7883#issuecomment-1772480997

I suggest to collect more experience before doing more work. The fear (at least from my side) was that there are way more problems that the few that users report. But if we stay at a handful a year, manual action is less effort than we already spent. I have plans to write a script to facilitate suspicious file checking, so that users (or CRAB team) can report trustable information to DataManagement operators who have the needed permissions to mark replicas bad.

**Comment by ivmfnal** [comment] 2023-10-20 12:06
@ericvaandering based on my conversation with Cedric, some time ago I made this [proposal](https://docs.google.com/document/d/1R9n1c2s1iXeCel5bHDTz7xPWdVVhZOqkUQv4o2PUaxs/edit?usp=sharing). The idea is to use the replica recoverer to move replicas from suspicious to bad.

Here is my summary on how to configure the replica recoverer: https://github.com/dmwm/CMSRucio/issues/403#issuecomment-1665583048

**Comment by belforte** [comment] 2023-11-13 15:40
I had the wrong permission in the directory where read failure error reports are collected.
I have now collected 11 truncated files in a few hours :-(
I have a script which runs overall those reports, but so fare only makes daily summaries, not particularly good to read. @ivmfnal are we ready for me to add a suspicious replica report ? In cases where root says file blahblah.root is truncated at 1542455296 bytes: should be 2672978503, there is not much to argue, I presume. I can add size check via gfal-ls e.g. but once that says that side is different from what Rucio memorized... no point is doing more, right ?
IIUC we can't report a reason for suspicious replicas, shall we look into marking those as BAD directly ?

**Comment by belforte** [comment] 2023-11-17 16:01
I have now setup some automated reporting pipeline, and waiting for suggestions from DM ops and experts in here on how to progress.
Please see: https://its.cern.ch/jira/browse/CMSTRANSF-766

I think am stuck since:
1) I do not have permission to mark replica as BAD myself, nor really want to
2) If those bad replicas are not marked and resolved "prompty" we end up with some kind of "home grown DB" to keep track which is the last thing I want to do
3) my scripts are meant to give us a sense of what's going on and show what is possible. But are not really a solid tool to be used for years to come. I know that I am not a good developer and will be more than happy if someone takes over.

Overall I think that in respect to Atlas we have:
- better inormation (truncated, not a ROOT file, potential read error)
- no indication of the source from CMSSW due to xroot fall-back, when we detect a possibly corrupted LFN we do not know where the replica is
- once we go through the trouble of checking all replicas to find the one which potentially caused the error, we know enough to take action if needed

So we need either a smarter Replica Recover daemon or something in the middle like what I scripted here, but I have got very cold about what to expect from current Rucio. The ReplicaRecover could have a great role for replicas found bad or missing during transfers. I am quite puzzled that there is no automatism there yet.

In any case I have reached the limit of what CRAB support can do

Please, step in.

**Comment by belforte** [comment] 2023-11-17 16:05
Since my time and patience are limited, I have setup crontabs to update all of that daily.
Access to information is unified by this Grafana panel
https://monit-grafana.cern.ch/d/CsnjLe6Mk/crab-overview?orgId=11&refresh=1h&from=1700063958182&to=1700236758182&viewPanel=116

IMHO it would make a lot of sense that DM operators have a look daily and if they agree, declare BAD replicas a suggested after all additional checks that they consider relevant.

I hope with this I can stop answering user reports of corrupted files.

**Comment by haozturk** [comment] 2024-05-28 09:19
I'll close this one as we have roadmap. Will track this effort at https://github.com/dmwm/CMSRucio/issues/805

**Closed by haozturk** 2024-05-28 09:19 UTC
Labels: waiting
