### ISSUE TITLE
Overwrite 2038 timestamp on access dataset timestamp in monitoring 

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#439] opened 2023-03-21 10:50 UTC
Not sure at which level of the toolchain this should happen, but we should focus on getting the right information into our monitoring system. What do you think @yuyiguo ? which options do we have for this? Do we have an open issue somewhere already?

For reference, [this](https://mattermost.web.cern.ch/cms-o-and-c/pl/sy5cg4gm4pr99enyu89wz6gs5o) is the MM dissussion that triggered this requests

**Comment by yuyiguo** [comment] 2023-03-21 16:39
I am not sure I understood the problem, but from the MM discussion, it seemed that the problem was a bug in Granfana (https://mattermost.web.cern.ch/cms-o-and-c/pl/nan1h5h5mjfa3y4kzdmyyp4cfe) . So this ticket can be closed? @dciangot

**Comment by yuyiguo** [comment] 2023-03-22 14:03
Ok, Thanks @belforte for explaining the problem.
Can you or someone let me what the files DIDs and what the last-accessed-time?  should be? 01/01/2018?

**Comment by yuyiguo** [comment] 2023-03-22 17:02
I would prefer to only change the confirmed rows because this is production DB.

**Comment by mrceyhun** [comment] 2023-03-22 17:51
@yuyiguo I think you can find them easily with a simple SQL query. Just query the `accessed_at` greater than current timestamp. For instance:
`select count(*) from CMS_RUCIO_PROD.REPLICAS where ACCESSED_AT>=DATE '2023-03-25'` (3 days of safety :) )

**Comment by yuyiguo** [comment] 2023-03-22 18:44
What date you want to change to?

**Comment by yuyiguo** [comment] 2023-03-22 18:50
If the files came to Rucio in 2018, why they showed as a problem now?  Do you know all the DIDs have future dates from 2018?

**Comment by mrceyhun** [comment] 2023-03-22 18:56
@yuyiguo I want to help you but unfortunately I don't know better than you. I can provide you the DIDs but I will use above query that I shared. And I don't know which date they should be set. From a monitoring point of view, I don't see a difference between setting their accessed at as 2018 or NULL :) This is just my opinion.

**Comment by yuyiguo** [comment] 2023-03-22 19:49
Looked into the DB, and we have 475 dids that have `accessed_at > 01-Jan-38`. Some of them were just updated yesterday/2023-03-21 10:15:16.  A lot of the were created in 2020.  Why is their accessed_at  set to 2038? People don't want the data to be deleted?  They looked like all mc data, ex name: /`store/mc/Run3Winter20DRMiniAOD/DoublePhoton_FlatPt-1000To1500/AODSIM/FlatPU0to80_110X_mcRun3_2021_realistic_v6-v1/110000/9231CCE7-0662-1C4D-965C-B5E530405CC8.root` .

**Comment by yuyiguo** [comment] 2023-03-22 20:19
475 files are not as few files as we originally understood. I checked in DBS and they were generated by the prod system/wmagent@vocms0280.cern.ch.  Unless we prevent people to put the date as what they want to, we may get more of these kinds of dates.  

Can you adjust your monitoring to ignore accessed_at > now+1hour instead of changing the DB?

**Comment by belforte** [comment] 2023-03-22 20:49
Yes. People/tools should not put junk in the DB.
I can't see how setting an access_at in the far future may be intentional. Can Rucio experts follow up with WMAgent experts and get things under control.
You are right Yuyi that we do no know exactly how those dates got into the system. Which is why nobody could give you a clear directive yet.

**Comment by yuyiguo** [comment] 2023-03-23 18:45
We will have a CMS rucio meeting next Tuesday and I will bring up this issue. 
@mrceyhun, is this prevent you from developing monitoring tools?  Can you ignore anything larger than the current time in your code?  
One compermise I could do if you could not handel this in monitoring would set the access_at to the updated_at.  As I said ealier, I prefer not to change prod data without understanding the cause.

**Comment by Panos512** [comment] 2023-03-24 09:10
@yuyiguo I would be very interested to join as well. I'm trying to figure out how all those traces end up in Rucio and what we should do to be able to trust this `last_accessed` attribute. What time is the meeting? The usual 15.15?

**Comment by yuyiguo** [comment] 2023-03-24 14:43
@Panos512 yes, it is the usual 15:15 on Tuesdays. See you then.

**Comment by belforte** [comment] 2023-03-28 07:59
@yuyiguo please note that `rucio list-rules --traverse` does not work for files.  See [this](https://mattermost.web.cern.ch/cms-o-and-c/pl/5dzy79irm7r6dguuk56ww1kp1h) from @dynamic-entropy

**Comment by amaltaro** [comment] 2023-03-28 10:25
Apologies for joining this thread a bit late. I am somehow confused as of what problem is actually being reported here.

I had a look at one of the LFNs that Yuyi provided in her text file above, which I also copy here the DBS query:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?logical_file_name=/store/mc/RunIIAutumn18MiniAOD/GluGluToRadionToHHTo2G2l2nu_M-250_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/270000/0F7299A2-C57A-344B-96F4-15E875A0E54C.root&detail=true

and the only time related attribute is `last_modification_date`, which is correctly set to 2020.

Can someone please clarify what is the problem and in which system (is it DBS or Rucio?). Thanks!

**Comment by belforte** [comment] 2023-03-28 10:54
You are confusing things Alan. This has nothing to do with modification time in dbs

**Comment by belforte** [comment] 2023-03-28 13:28
@amaltaro the issue is about last time a file was read, which is tracked in Rucio in order to decide when to delete an unlocked file.

**Comment by yuyiguo** [comment] 2023-03-28 14:22
We just talked about the issue in Rucio's meeting.  The date 2038-01-19 is the max int number to unix timestamp. I will check where this may come into the system. My plan is to change them to the last_modification_date.

**Comment by amaltaro** [comment] 2023-03-28 15:07
Thanks Stefano and Yuyi for clarifying it.

The only moment that WMAgent updates a file (replica?) information is when the replica is actually created. Looking at that code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/RucioInjector/RucioInjectorPoller.py#L300-L302

the only replica attributes that are defined in the agent are: name, scope, bytes, state, adler32. Other attributes either come from Rucio default values or from different tools acting on these replicas.

If you need any other information from WM, please let me know, otherwise I would say WM is not the one defining these strange timestamps.

**Comment by yuyiguo** [comment] 2023-03-28 15:09
Thank you Alan for the WMAgent info.

**Comment by yuyiguo** [comment] 2023-03-28 16:28
Following up with the discussion at the Rucio meeting today:
- Verified the `accesse_at` in the database `2038-01-19 03:14:07` has its unix timestamp as 2,147,483,647 which is exactly the int32 max value.  
- Checked in the Rucio tracer code.  We have the `[ts](https://github.com/dmwm/rucio-tracers/blob/main/stompserver/traceDef.go#L31) `defined as int64 instead of int32 .
- Checked we [convert](https://github.com/dmwm/rucio-tracers/blob/main/stompserver/traceDef.go#L51) milliseconds to seconds before we make a trace.
-  Rucio tracer gets trace info from three different sources.  If they have the timestamps, the tracer will use them.  If not, the tracer will use the current timestamp. The question now is how the sources define their data.
- `WMArchive: /topic/cms.jobmon.wmarchive` : Tracer gets the data from [Metadata.Ts](https://github.com/dmwm/rucio-tracers/blob/main/stompserver/fwjrTracer.go#L119). 
- `CMSSWPOP: /topic/cms.swpop` and `xrootd: /topic/xrootd.cms.aaa.ng`: tracer gets the data from the [Ts](https://github.com/dmwm/rucio-tracers/blob/main/stompserver/traceMaker.go#L151) field in the messages. 
I could update the tracer to ignore any timestamps that are greater than the current time+12 hours or something like that, but we will lose the valid time. So I would ask the data source developers to check their side to make sure to use int64 if milliseconds are used. 
@vkuznet, can you check WMArchive? I don't know whom to contact for xrootd and swpop.  @nsmith- , @klannon , @ericvaandering , @dciangot , anyone can point me to the right contact persons? 
Meanwhile, I will update the database for the existing 2038 timestamps using `last_modification_date`.

**Comment by ericvaandering** [comment] 2023-03-28 16:34
I guess I would say that anything saying it accessed a file more than 18 hours in the future is lying and should be mapped to the current time.

**Comment by yuyiguo** [comment] 2023-03-28 19:05
Valentin, thank you for your quick response. Rucio tracer uses WMArchive meta_data.ts that is in seconds since epoch.  It's in the right data type too.  So the problem was not from WMArchive.

The problem is caused by a source that uses milliseconds since epoch with data type int32. Then, Rucio will get a timestamp `2038-01-19 03:14:07 `.

**Comment by yuyiguo** [comment] 2023-03-28 21:14
More studies found the odd `accessed_at=2038-01-19 03:14:07 ` are not from rucio tracer.  We use one file as an example to demonstrate this conclusion.
```
RSE_ID	SCOPE	NAME	BYTES	MD5	ADLER32	PATH	STATE	LOCK_CNT	ACCESSED_AT	TOMBSTONE	UPDATED_AT	CREATED_AT
"2694B6BD279F4BAA890F5ABBE66351D2"	"cms"	"/store/mc/RunIISummer16MiniAODv3/ZH_HToZZTo2Nu2X_2LFilter_4LVeto_M210_TuneCUETP8M1_13TeV_powheg2-minlo-HZJ_JHUGenV735_pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/280000/402192B0-9AF2-EA11-ACE3-AC1F6BD5A0DE.root"	477003379	(null)	"aa5a7a03"	(null)	"A"	0	"2038-01-19 03:14:07"	"2038-01-19 03:14:07"	"2023-03-21 11:49:04"	"2020-09-22 09:55:32"
```
The file was `created_at=2020-09-22 09:55:32`, but rucio tracer was created around Sep 2021. So this file was already in the rucio for a year before the tracer was created. Then the file was `updated_at=2023-03-21 11:49:04`. Who/what updated the file? For sure it was not the tracer because `updated_at` is not in the trace definition so the tracer will not change `updated_at`. I suspect that `accessed_at` was changed when the `updated_at` was changed. The same file has tree replicas and only the one with the new `update_at=2023-03-21 11:49:04` has  `accessed_at=2038-01-19 03:14:07`.
```
RSE_ID	SCOPE	NAME	BYTES	MD5	ADLER32	PATH	STATE	LOCK_CNT	ACCESSED_AT	TOMBSTONE	UPDATED_AT	CREATED_AT
F44C866A264D4DA9972969E9F3B5BB52	cms	/store/mc/RunIISummer16MiniAODv3/ZH_HToZZTo2Nu2X_2LFilter_4LVeto_M210_TuneCUETP8M1_13TeV_powheg2-minlo-HZJ_JHUGenV735_pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/280000/402192B0-9AF2-EA11-ACE3-AC1F6BD5A0DE.root	477003379	(null)	aa5a7a03	(null)	A	1	(null)	(null)	2020-10-06 10:59:08	2020-10-06 10:59:08
DBDAF50EE9D24F92AD24473539522204	cms	/store/mc/RunIISummer16MiniAODv3/ZH_HToZZTo2Nu2X_2LFilter_4LVeto_M210_TuneCUETP8M1_13TeV_powheg2-minlo-HZJ_JHUGenV735_pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/280000/402192B0-9AF2-EA11-ACE3-AC1F6BD5A0DE.root	477003379	(null)	aa5a7a03	(null)	A	1	(null)	(null)	2020-10-29 22:04:32	2020-10-29 22:04:32
2694B6BD279F4BAA890F5ABBE66351D2	cms	/store/mc/RunIISummer16MiniAODv3/ZH_HToZZTo2Nu2X_2LFilter_4LVeto_M210_TuneCUETP8M1_13TeV_powheg2-minlo-HZJ_JHUGenV735_pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/280000/402192B0-9AF2-EA11-ACE3-AC1F6BD5A0DE.root	477003379	(null)	aa5a7a03	(null)	A	0	2038-01-19 03:14:07	2038-01-19 03:14:07	2023-03-21 11:49:04	2020-09-22 09:55:32

```
I will continue to contact the swpop and xrootd AMQ developers to make sure we get the correct timestamps from them.

**Comment by yuyiguo** [comment] 2023-03-28 21:30
All 473 replicas that have accessed_at > Jan-1-2038 are updated as below:
```
update replicas
set accessed_at=updated_at, tombstone=updated_at
WHERE accessed_at > to_date('01-Jan-38','DD-MON-YY') ;
```

**Comment by yuyiguo** [comment] 2023-04-03 18:31
The table was updated. I did not get additional info and my investigation showed that the 2038 timestamps were not from rucio traces. So I am closing this ticket. Reopen it if new info appears.

**Comment by dynamic-entropy** [comment] 2023-06-28 10:13
Hi @yuyiguo 
Is there more to be done here? Was the reopening of the issue intentional?
I see that the `accessed_at` fields did not get any new 2038 timestamps after you corrected them.

**Comment by yuyiguo** [comment] 2023-06-28 13:54
It is done but forgot to close it. Close now.

**Closed by yuyiguo** 2023-06-28 13:54 UTC
Labels: bug, triage
