### ISSUE TITLE
Investigate possible CE procedures failures at RAL

### ISSUE THREAD

**Issue by ivmfnal** [dmwm/CMSRucio#319] opened 2022-08-16 15:43 UTC
There is an impression that Consistency Enforcement procedures do not seem to have an effect for RAL disk and tape, while the detection part seems to be working correctly.

1. Determine if that is actually the case and the actions do not actually work
2. Diagnose the problem, if it exists
3. Correct the problem if possible
     - Currently the strategy is: if modifications of existing CE actions are required, do not do anything until the daemon-less CE code is in place

(1) may be related to #318  (Improve CE Monitoring)

**Comment by KatyEllis** [comment] 2022-08-19 17:28
I do believe that the CE is working for Missing files on RAL Tape (action for Dark files is not yet activated). The issue is only with RAL Disk.

**Comment by KatyEllis** [comment] 2022-08-19 17:33
![Screenshot 2022-08-19 at 16 26 07](https://user-images.githubusercontent.com/43205441/185674482-7060bde1-cbb9-4c76-b97f-bcdeb707dbda.png)
Image shows the last couple of consistency checks at RAL Disk. You can see that the number of Missing files is reducing (and a few new ones may be added) each week. This may be evidence that the CE is doing something. 

But the number of files that are actually removed from the Missing list each week seems small. I am curious about the files that are sitting in this list week after week, and why CE is not dealing with them. I can investigate a little on my side to see if other replicas are trying and failing to transfer. But I'm not seeing a lot of transfer failures to RAL Disk (for Recovery activity or otherwise).

**Comment by ivmfnal** [comment] 2022-08-25 18:18
Having spent some time debugging CE daemons, I noticed that generally are failing for different reasons for different sites, but most of errors are like this:

```
Details: (cx_Oracle.DatabaseError) ORA-00904: "RSE_PROTOCOLS"."THIRD_PARTY_COPY": invalid identifier
[SQL: SELECT rse_protocols.hostname AS rse_protocols_hostname, rse_protocols.scheme AS rse_protocols_scheme, rse_protocols.port AS rse_protocols_port, rse_protocols.prefix AS rse_protocols_prefix, rse_protocols.impl AS rse_protocols_impl, rse_protocols.read_lan AS rse_protocols_read_lan, rse_protocols.write_lan AS rse_protocols_write_lan, rse_protocols.delete_lan AS rse_protocols_delete_lan, rse_protocols.read_wan AS rse_protocols_read_wan, rse_protocols.write_wan AS rse_protocols_write_wan, rse_protocols.delete_wan AS rse_protocols_delete_wan, rse_protocols.third_party_copy AS rse_protocols_third_part_1, rse_protocols.extended_attributes AS rse_protocols_extended_a_2 
FROM rse_protocols 
WHERE rse_protocols.rse_id = :rse_id_1]
[parameters: {'rse_id_1': b'\xb2K\xe8.\x1a\x1eF\xdd\x92\xb9#]\x91\xf8\xfd\x8d'}]
```
The way I interpret this error, the rucio.core modules used by the daemons are not compatible with current DB schema

For RAL, specifically, the error is different. The daemon creates this intermediate file with dark replica paths. For some reason, this file contains an empty line. When the daemon reads this file back, it fails to parse the empty line and exits with exception.

**Comment by KatyEllis** [comment] 2022-08-26 13:19
Ah interesting, Igor. Can you remind me, when will you deploy the new code we have discussed previously? IIRC you weren't going to make a lot of changes to the current code since we have a whole new code set almost ready.

**Comment by ivmfnal** [comment] 2022-08-26 13:27
The plan was to test/debug the new code over this week and make the decision early next week

**Comment by ivmfnal** [comment] 2022-08-29 12:05
After fixing the blank line bug mentioned above, CE actions for RAL are now same as for other sites - incompatibility between rucio.core and the DB schema

**Comment by KatyEllis** [comment] 2022-12-13 14:51
The missing file actions are now working on RAL Disk. In recent weeks there have been zero missing files found by consistency check. 
For the dark data on RAL Disk, it's a little worrying that the number of files always remains at several thousand files even though actions are carried out every week on several thousand files. Of course this may not be a consistency checking problem - but indicate a different problem.

**Comment by dynamic-entropy** [comment] 2024-05-02 10:44
Closing, this is marked done on the project board. 
I believe we have newer issues to be resolved for RAL, will create a new ticket with more information for that.

**Closed by dynamic-entropy** 2024-05-02 10:44 UTC
