### ISSUE TITLE
Rucio `list-dataset-replicas` returns different response w/ and w/o `--deep` flag

### ISSUE THREAD

**Issue by haozturk** [dmwm/CMSRucio#257] opened 2022-03-04 16:25 UTC
Here are two examples:
```
$ rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228

DATASET: cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_EE_Estonia      |       0 |     500 |
| T2_US_UCSD         |       0 |     500 |
| T2_ES_CIEMAT       |       0 |     500 |
| T2_FR_IPHC         |       0 |     500 |
| T2_IT_Rome         |       0 |     500 |
| T1_FR_CCIN2P3_Tape |     500 |     500 |
| T2_US_MIT          |       0 |     500 |
| T2_IT_Legnaro      |       0 |     500 |
| T2_US_Florida      |       0 |     500 |
| T0_CH_CERN_Tape    |     500 |     500 |
| T2_UK_SGrid_RALPP  |       0 |     500 |
| T2_US_Vanderbilt   |       0 |     500 |
| T1_US_FNAL_Disk    |       0 |     500 |
+--------------------+---------+---------+


$ rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228 --deep

DATASET: cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_CN_Beijing      |     500 |     500 |
| T1_FR_CCIN2P3_Tape |     500 |     500 |
| T0_CH_CERN_Tape    |     500 |     500 |
+--------------------+---------+---------+
```
&
```
$ rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0

DATASET: cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_EE_Estonia      |       0 |     124 |
| T2_US_UCSD         |       0 |     124 |
| T2_ES_CIEMAT       |       0 |     124 |
| T2_FR_IPHC         |       0 |     124 |
| T2_IT_Rome         |       0 |     124 |
| T1_FR_CCIN2P3_Tape |     124 |     124 |
| T2_US_MIT          |       0 |     124 |
| T2_IT_Legnaro      |       0 |     124 |
| T2_US_Florida      |       0 |     124 |
| T0_CH_CERN_Tape    |     124 |     124 |
| T2_UK_SGrid_RALPP  |       0 |     124 |
| T2_US_Vanderbilt   |       0 |     124 |
| T1_US_FNAL_Disk    |       0 |     124 |
+--------------------+---------+---------+

$ rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0 --deep

DATASET: cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_CN_Beijing      |     124 |     124 |
| T1_FR_CCIN2P3_Tape |     124 |     124 |
| T0_CH_CERN_Tape    |     124 |     124 |
+--------------------+---------+---------+
```

Note that this input is no longer needed as of today, so it is possible that it'll be deleted from Beijing soon.

**Comment by yuyiguo** [comment] 2022-03-04 16:46
Do you have another examples other than Beijing one?

**Comment by yuyiguo** [comment] 2022-03-04 16:47
wrote by Alan and copied from Slack 
Hi everyone, we have been noticing in CMS that the list_dataset_replicas API returns a different result when setting the deep flag to True/False, which sometimes remain inconsistent for days.
In our WM data location plus data lock logic, we actually want to make sure that the dataset availability belongs to a given set of rules/locks, thus we call:
the list_replication_rulesfirst, with a set of parameters like account, did, grouping, etc
then we call get_dataset_locks and match those rule ids against the rules gathered in step 1.
My question is, would the output of this get_dataset_locks also be affected by the replica-based information (similar to when using deep=True , when listing dataset replicas)?

**Comment by yuyiguo** [comment] 2022-03-04 16:51
@haozturk Can you detail the  call` list_replication_rules` and `get_dataset_locks `?

**Comment by yuyiguo** [comment] 2022-03-04 18:10
@ericvaandering 
I could not find the two dids (`/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0 `and `/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228`) in the `REPLICAS `or `REPLICAS_HISTORY` table. I did find them in `COLLECTION_REPLICAS `table  with RES in Fr and CERN, but not Beijing. The updated dates are back to 2020. Why can not find them at all in `REPLICAS `or `REPLICAS_HISTORY` table? Can you explain how rucio data moves here?

**Comment by amaltaro** [comment] 2022-03-04 18:31
@yuyiguo @haozturk I just wanted to provide this example, from a command that I ran early this morning and which is still in my terminal:
```
amaltaro@lxplus751:~ $ rucio list-rules "cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0"
ID                                ACCOUNT                  SCOPE:NAME                                                            STATE[OK/REPL/STUCK]    RSE_EXPRESSION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              COPIES  EXPIRES (UTC)    CREATED (UTC)
--------------------------------  -----------------------  --------------------------------------------------------------------  ----------------------  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  --------  ---------------  -------------------
afdb7ce886144c1195025e6bb92d32c4  sync_t0_ch_cern_tape     cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0  OK[124/0/0]             rse=T0_CH_CERN_Tape                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1                   2020-09-29 15:42:33
c17a3c427f294022b99daa88b9bf1a6b  sync_t1_fr_ccin2p3_tape  cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0  OK[124/0/0]             rse=T1_FR_CCIN2P3_Tape                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1                   2020-09-28 09:21:34
7af5a0dfe6864d0d9b315bd946cc4f96  wmcore_transferor        cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0  OK[124/0/0]             T2_US_Vanderbilt|T2_KR_KISTI|T2_UK_London_IC|T2_US_Purdue|T2_US_Nebraska|T2_FI_HIP|T2_IT_Legnaro|T2_RU_INR|T2_FR_GRIF_LLR|T2_DE_RWTH|T1_RU_JINR_Disk|T2_FR_GRIF_IRFU|T1_FR_CCIN2P3_Disk|T2_CH_CERN|T2_HU_Budapest|T2_US_Wisconsin|T2_BE_UCL|T2_PL_Swierk|T2_DE_DESY|T2_IT_Rome|T2_CN_Beijing|T2_US_Florida|T2_ES_IFCA|T2_PT_NCG_Lisbon|T2_IT_Bari|T2_US_Caltech|T2_ES_CIEMAT|T2_UA_KIPT|T1_IT_CNAF_Disk|T1_DE_KIT_Disk|T2_UK_SGrid_RALPP|T2_BE_IIHE|T2_RU_JINR|T2_CH_CSCS|T1_ES_PIC_Disk|T2_US_MIT|T2_BR_UERJ|T2_FR_IPHC         1                   2022-01-28 17:29:32
```

where we can see that those 3 rules have actually being fully satisfied (see `OK[124/0/0]`). Yet, `list-dataset-replicas` list this block as available only at those 2 Tape endpoints.

**Comment by haozturk** [comment] 2022-03-07 15:08
> Do you have another examples other than Beijing one?
No, but I haven't checked all the datasets. We can spot the issues if there is a stuck workflow in the system whose input suffers from this problem.

> Can you detail the call list_replication_rules and get_dataset_locks ?
I haven't checked the python rucio client queries. I've just checked CLI `list-dataset-replicas`.

**Comment by yuyiguo** [comment] 2022-03-07 17:48
```
rucio rule-info c17a3c427f294022b99daa88b9bf1a6b 
Id:                         c17a3c427f294022b99daa88b9bf1a6b
Account:                    sync_t1_fr_ccin2p3_tape
Scope:                      cms
Name:                       /SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
RSE Expression:             rse=T1_FR_CCIN2P3_Tape
Copies:                     1
State:                      OK
Locks OK/REPLICATING/STUCK: 124/0/0
Grouping:                   DATASET
Expires at:                 None
Locked:                     True
Weight:                     None
Created at:                 2020-09-28 09:21:34
Updated at:                 2020-09-28 09:21:34
Error:                      None
Subscription Id:            None
Source replica expression:  None
Activity:                   Data Consolidation
Comment:                    None
Ignore Quota:               False
Ignore Availability:        False
Purge replicas:             False
Notification:               NO
End of life:                None
Child Rule Id:              None

```

**Comment by yuyiguo** [comment] 2022-03-07 17:49
```
rucio rule-info afdb7ce886144c1195025e6bb92d32c4
Id:                         afdb7ce886144c1195025e6bb92d32c4
Account:                    sync_t0_ch_cern_tape
Scope:                      cms
Name:                       /SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
RSE Expression:             rse=T0_CH_CERN_Tape
Copies:                     1
State:                      OK
Locks OK/REPLICATING/STUCK: 124/0/0
Grouping:                   DATASET
Expires at:                 None
Locked:                     True
Weight:                     None
Created at:                 2020-09-29 15:42:33
Updated at:                 2020-09-29 15:42:34
Error:                      None
Subscription Id:            None
Source replica expression:  None
Activity:                   Data Consolidation
Comment:                    None
Ignore Quota:               False
Ignore Availability:        False
Purge replicas:             False
Notification:               NO
End of life:                None
Child Rule Id:              None
```

**Comment by yuyiguo** [comment] 2022-03-07 17:50
@bari12 see above rule infos.

**Comment by bari12** [comment] 2022-03-08 08:28
Thanks, and `/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0` is this a dataset or container? 
Also how is this filled usually? At the point when the rule is created, are there already files in it? (All of them?) Or is the did created + rule created and files are only filled afterwards?

**Comment by yuyiguo** [comment] 2022-03-14 18:06
When I re-ran the commands without --deep and T2_CN_Beijing was showed up.
`rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228
DATASET: cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_EE_Estonia      |       0 |     500 |
| T2_US_UCSD         |       0 |     500 |
| T2_ES_CIEMAT       |       0 |     500 |
| T2_FR_IPHC         |       0 |     500 |
| T2_CN_Beijing      |     500 |     500 |
| T1_FR_CCIN2P3_Tape |     500 |     500 |
| T2_US_MIT          |       0 |     500 |
| T2_IT_Legnaro      |       0 |     500 |
| T2_IT_Rome         |       0 |     500 |
| T2_US_Florida      |       0 |     500 |
| T0_CH_CERN_Tape    |     500 |     500 |
| T2_UK_SGrid_RALPP  |       0 |     500 |
| T2_US_Vanderbilt   |       0 |     500 |
| T1_US_FNAL_Disk    |       0 |     500 |
+--------------------+---------+---------+

`

**Comment by yuyiguo** [comment] 2022-03-14 18:09
```
rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
DATASET: cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_EE_Estonia      |       0 |     124 |
| T2_US_UCSD         |       0 |     124 |
| T2_ES_CIEMAT       |       0 |     124 |
| T2_FR_IPHC         |       0 |     124 |
| T2_CN_Beijing      |     124 |     124 |
| T1_FR_CCIN2P3_Tape |     124 |     124 |
| T2_US_MIT          |       0 |     124 |
| T2_IT_Legnaro      |       0 |     124 |
| T2_IT_Rome         |       0 |     124 |
| T2_US_Florida      |       0 |     124 |
| T0_CH_CERN_Tape    |     124 |     124 |
| T2_UK_SGrid_RALPP  |       0 |     124 |
| T2_US_Vanderbilt   |       0 |     124 |
| T1_US_FNAL_Disk    |       0 |     124 |
+--------------------+---------+---------+

```

**Comment by amaltaro** [comment] 2022-03-15 02:44
> I have a suspicion. In your example, do you think the replicas for the rule which includes T2_CN_Beijing (7af5a0dfe6864d0d9b315bd946cc4f96) were all already in place on storage when creating the rule?

Hi Martin, I don't think I am able to answer this question. Is there anywhere or any API that we could use to see a "snapshot" for a time in the long past?

>  That was why we did not see it w/o --deep 10 days ago. I don't know what is the process to register the dataset in a RSE to Rucio in CMS and who did what then the dataset in T2_CN_Beijing showed up in the table today?

Yuyi, I guess this is the problem that we are trying to sort out. The dataset replication eventually gets satisfied and moved to OK state. Apparently, for a very peculiar use case, it can take many days to be marked as OK though.

**Comment by bari12** [comment] 2022-03-15 17:09
ok thanks. That the rule including `T2_CN_Beijing` was the last one, refutes my theory a bit.

I think I understand more clearly now. For a dataset to have a collection_replica, there needs to be a rule on the dataset specifically for a collection replica to be created.

Let's say you have 5 identical datasets (Same files in all of them). If you create a rule for one of the datasets, this one will show up in the collection_replicas, the others won't. The reason for this is complexity, in principle you would have to check, for each single file in the dataset, the other parent_datasets and create collection_replicas for these as well. We decided against this though for complexity reason.

**Comment by yuyiguo** [comment] 2022-03-16 14:55
looked into this dataset `cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0 `again. Three is a new rule (`d8a93bd34f264f71844b66e8257c5439`)  created March 14.  And it was this new rule brought the dataset into collection_replicas table. At the time the new rule created, the dataset was already at the RSE `T2_CN_Beijing`. 
```
rucio list-rules "cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0"
ID                                ACCOUNT                  SCOPE:NAME                                                            STATE[OK/REPL/STUCK]    RSE_EXPRESSION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              COPIES  EXPIRES (UTC)    CREATED (UTC)
--------------------------------  -----------------------  --------------------------------------------------------------------  ----------------------  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  --------  ---------------  -------------------
afdb7ce886144c1195025e6bb92d32c4  sync_t0_ch_cern_tape     cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0  OK[124/0/0]             rse=T0_CH_CERN_Tape                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1                   2020-09-29 15:42:33
c17a3c427f294022b99daa88b9bf1a6b  sync_t1_fr_ccin2p3_tape  cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0  OK[124/0/0]             rse=T1_FR_CCIN2P3_Tape                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1                   2020-09-28 09:21:34
d8a93bd34f264f71844b66e8257c5439  wmcore_transferor        cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0  OK[124/0/0]             T2_DE_RWTH|T2_IT_Bari|T2_EE_Estonia|T1_IT_CNAF_Disk|T2_TR_METU|T1_FR_CCIN2P3_Disk|T2_CH_CSCS|T2_FR_IPHC|T2_US_UCSD|T2_US_Caltech|T2_US_Vanderbilt|T1_DE_KIT_Disk|T2_CN_Beijing|T2_US_Wisconsin|T1_RU_JINR_Disk|T2_HU_Budapest|T1_ES_PIC_Disk|T2_US_Purdue|T2_UK_SGrid_RALPP|T2_RU_JINR|T2_CH_CERN|T2_DE_DESY|T2_KR_KISTI|T2_UK_London_IC|T2_PL_Swierk|T1_UK_RAL_Disk|T2_IT_Legnaro|T2_US_MIT|T2_PT_NCG_Lisbon|T2_BR_UERJ|T2_ES_CIEMAT|T2_ES_IFCA|T2_BE_UCL|T2_US_Florida|T2_TW_NCHC|T2_RU_INR|T2_RU_IHEP                         1                   2022-03-14 12:04:31
7af5a0dfe6864d0d9b315bd946cc4f96  wmcore_transferor        cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0  OK[124/0/0]             T2_US_Vanderbilt|T2_KR_KISTI|T2_UK_London_IC|T2_US_Purdue|T2_US_Nebraska|T2_FI_HIP|T2_IT_Legnaro|T2_RU_INR|T2_FR_GRIF_LLR|T2_DE_RWTH|T1_RU_JINR_Disk|T2_FR_GRIF_IRFU|T1_FR_CCIN2P3_Disk|T2_CH_CERN|T2_HU_Budapest|T2_US_Wisconsin|T2_BE_UCL|T2_PL_Swierk|T2_DE_DESY|T2_IT_Rome|T2_CN_Beijing|T2_US_Florida|T2_ES_IFCA|T2_PT_NCG_Lisbon|T2_IT_Bari|T2_US_Caltech|T2_ES_CIEMAT|T2_UA_KIPT|T1_IT_CNAF_Disk|T1_DE_KIT_Disk|T2_UK_SGrid_RALPP|T2_BE_IIHE|T2_RU_JINR|T2_CH_CSCS|T1_ES_PIC_Disk|T2_US_MIT|T2_BR_UERJ|T2_FR_IPHC         1                   2022-01-28 17:29:32

```

```
rucio rule-info d8a93bd34f264f71844b66e8257c5439
Id:                         d8a93bd34f264f71844b66e8257c5439
Account:                    wmcore_transferor
Scope:                      cms
Name:                       /SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
RSE Expression:             T2_DE_RWTH|T2_IT_Bari|T2_EE_Estonia|T1_IT_CNAF_Disk|T2_TR_METU|T1_FR_CCIN2P3_Disk|T2_CH_CSCS|T2_FR_IPHC|T2_US_UCSD|T2_US_Caltech|T2_US_Vanderbilt|T1_DE_KIT_Disk|T2_CN_Beijing|T2_US_Wisconsin|T1_RU_JINR_Disk|T2_HU_Budapest|T1_ES_PIC_Disk|T2_US_Purdue|T2_UK_SGrid_RALPP|T2_RU_JINR|T2_CH_CERN|T2_DE_DESY|T2_KR_KISTI|T2_UK_London_IC|T2_PL_Swierk|T1_UK_RAL_Disk|T2_IT_Legnaro|T2_US_MIT|T2_PT_NCG_Lisbon|T2_BR_UERJ|T2_ES_CIEMAT|T2_ES_IFCA|T2_BE_UCL|T2_US_Florida|T2_TW_NCHC|T2_RU_INR|T2_RU_IHEP
Copies:                     1
State:                      OK
Locks OK/REPLICATING/STUCK: 124/0/0
Grouping:                   DATASET
Expires at:                 None
Locked:                     False
Weight:                     ddm_quota
Created at:                 2022-03-14 12:04:31
Updated at:                 2022-03-14 12:05:02
Error:                      None
Subscription Id:            None
Source replica expression:  None
Activity:                   Production Input
Comment:                    WMCore MSTransferor input data placement
Ignore Quota:               False
Ignore Availability:        False
Purge replicas:             False
Notification:               NO
End of life:                None
Child Rule Id:              None

```

**Comment by bari12** [comment] 2022-03-16 15:50
Is there some combination between rules created on container vs. dataset level?

**Comment by bari12** [comment] 2022-03-16 17:24
I am a bit confused by the timing here. E.g. I don't understand why it would just suddenly re-appear as Yuki described. A big backlog (`updated_col_rep` table) could explain this, but I don't think this is the case. Usually these things don't just suddenly unclog themselves - if this would be a problem, you would probably notice quickly.

From the workflow I think you are doing everything right. A rule on a container or dataset should create a collection replica for all datasets involved on the RSE the rule is pointing to. You are clearly doing this. In some cases it just does not create the collection replica.

What confuses me a bit, in the example above

```
$ rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0

DATASET: cms:/SingleMuon/Run2016H-v1/RAW#61b64000-89f9-11e6-9fb3-001e67ac06a0
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_EE_Estonia      |       0 |     124 |
| T2_US_UCSD         |       0 |     124 |
| T2_ES_CIEMAT       |       0 |     124 |
| T2_FR_IPHC         |       0 |     124 |
| T2_IT_Rome         |       0 |     124 |
| T1_FR_CCIN2P3_Tape |     124 |     124 |
| T2_US_MIT          |       0 |     124 |
| T2_IT_Legnaro      |       0 |     124 |
| T2_US_Florida      |       0 |     124 |
| T0_CH_CERN_Tape    |     124 |     124 |
| T2_UK_SGrid_RALPP  |       0 |     124 |
| T2_US_Vanderbilt   |       0 |     124 |
| T1_US_FNAL_Disk    |       0 |     124 |
+--------------------+---------+---------+
```

Does anyone have an explanation where all these 0 entries come from? I wonder if there is a connection. Or where these actually previously used RSEs for this data and the replicas where just removed in the meanwhile?

**Comment by amaltaro** [comment] 2022-03-16 18:05
> Is there some combination between rules created on container vs. dataset level?

We only create container-level rules (group=ALL) for pileup data.
All the rest of the input data (primary) goes through rucio dataset-level rules.

**Comment by yuyiguo** [comment] 2022-03-21 21:03
I had discussion with Eric last Thursday.  I read the `PROCEDURE "COLL_REPLICAS_UPDATE_ALL"` again and confirm that this procedure does not delete the rows in `UPDATED_COL_REP` table if the table has more than 5k rows. The procedure will `bulk_collect `5k each time and repeated running it will eventually handle all the rows in `UPDATED_COL_REP` table. So I don't think that stopped running this procedure for a while last November would affect the problem we had two weeks ago because Kate ran it through. @bari12, please correct me if I understood wrong.  In addition, can you explain which API/call actually add datasets into "collection_replicas" table?  Below code is are from `PROCEDURE "COLL_REPLICAS_UPDATE_ALL"`. This indicates that the dataset is already in "collection_replicas"  before it can be updated.
```
-- Delete Update requests which do not have Collection_replicas

    DELETE FROM UPDATED_COL_REP A WHERE A.rse_id IS NOT NULL AND NOT EXISTS(SELECT * FROM COLLECTION_REPLICAS B WHERE B.scope = A.scope AND B.name = A.name  AND B.rse_id = A.rse_id);

    DELETE FROM UPDATED_COL_REP A WHERE A.rse_id IS NULL AND NOT EXISTS(SELECT * FROM COLLECTION_REPLICAS B WHERE B.scope = A.scope AND B.name = A.name);
```
@amaltaro I will schedule a short meeting with you to talk about the steps WM request datasets from Rucio.

**Comment by yuyiguo** [comment] 2023-06-29 19:37
This problem was concluded that might be caused by an incorrectly created rule. In addition, we hadn't found anything like this after. 
@dynamic-entropy, there is no point to reassign these tickets around. Please close it directly.

**Closed by yuyiguo** 2023-06-29 19:37 UTC

**Comment by ericvaandering** [comment] 2023-06-29 19:39
I asked Rahul not to just close any tickets. I'd like the person most expert on the issue to close the ticket.
