### ISSUE TITLE
Add a section for prometheus setup to operator instructions

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#664] opened 2023-12-01 22:39 UTC
Maybe just link to what we have in rucio-flux

**Comment by ericvaandering** [comment] 2023-12-01 22:58
https://github.com/dmwm/rucio-flux/tree/main/infrastructure/prometheus

**Comment by ericvaandering** [comment] 2024-03-22 12:34
Added https://gitlab.cern.ch/cmsdmops/Documentation/-/merge_requests/23

**Comment by klannon** [comment] 2024-06-11 02:01
@ericvaandering This is marked as done, but the issue is still open.  Should it be closed?

**Closed** 2024-06-11 14:55 UTC
