### ISSUE TITLE
Bug in the OIDC sync script

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#474] opened 2023-04-20 18:20 UTC
The daily cron job (https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/scripts/k8s_sync_users_links.sh) fails with the following trace. 

```
+ echo 'Syncing OIDC user identities'
+ ./syncaccount_oidc.py
ERROR oidc-agent: No account configured with that short name
Traceback (most recent call last):
  File "./syncaccount_oidc.py", line 105, in <module>
    headers = {'Authorization': 'Bearer %s' % token, 'Content-type': 'application/json' }
NameError: name 'token' is not defined
```

**Comment by dciangot** [comment] 2023-04-20 18:30
duplicate of #428 i think

**Closed by dciangot** 2023-04-20 18:30 UTC
